# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['_a_main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('images', 'images'),
        ('qtDesigner', 'qtDesigner'),
        ('database', 'database'),
        ('hooks', 'hooks'),
        ('states', 'states'),
        ('GetSelectedObjects', 'GetSelectedObjects'),
        ('Planes', 'Planes'),
        ('PlottingFunctions', 'PlottingFunctions'),
        ('SpreadsheetFunctions', 'SpreadsheetFunctions'),
    ],
    hiddenimports=[
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.uic',
        'comtypes.client',
        'numpy',
        'pandas',
        'matplotlib',
        'openpyxl',
        'PyPDF2',
        'qtDesigner.windowLoadModel',
        'qtDesigner.windowModules',
        'qtDesigner.windowSelectViews',
        'qtDesigner.converter',
        'states.statesAllRequests',
        'states.statesUI',
        'hooks.csiHooks',
        'hooks.AnalysisResultsHooks',
        'hooks.basicHooks',
        'hooks.qtDesignerHooks',
        'hooks.tableWidgetHooks',
        'hooks.viewLabelsDialogHook',
        'database.csiTables',
        'database.tableSetup',
        'GetSelectedObjects.SelectedAreas',
        'GetSelectedObjects.SelectedFrames',
        'GetSelectedObjects.SelectedPoints',
        'Planes.PlaneFunctionsHooks',
        'PlottingFunctions.PlotColumnsAndBraces',
        'PlottingFunctions.PlotPointParameters',
        'PlottingFunctions.PlotStructure',
        'PlottingFunctions.PlotStructure2',
        'PlottingFunctions.PlotText',
        'PlottingFunctions.PlotVectors',
        'PlottingFunctions.PlotVectorsAndPointParameters',
        'SpreadsheetFunctions.BaseReactionFunction',
        'SpreadsheetFunctions.CompositeBeamDesignFunction',
        'SpreadsheetFunctions.DiaphragmBraceForcesFunction',
        'SpreadsheetFunctions.DiaphragmForcesFunction',
        'SpreadsheetFunctions.EndForcesFunction',
        'SpreadsheetFunctions.FramingPlanFunctions',
        'SpreadsheetFunctions.JointDisplacementFunction',
        'SpreadsheetFunctions.JointDriftFunction',
        'SpreadsheetFunctions.JointReactionFunction',
        'SpreadsheetFunctions.MaxFrameForcesFunction',
        'SpreadsheetFunctions.ModalPropertiesFunction',
        'SpreadsheetFunctions.ModifierFunctions',
        'SpreadsheetFunctions.ReleasesFunctions',
        'SpreadsheetFunctions.SteelDesignFunctions',
        'SpreadsheetFunctions.StoryForcesFunction',
        'SpreadsheetFunctions.LoadAssigns.AreaLoadAssignmentsUniform',
        'SpreadsheetFunctions.LoadAssigns.FrameLoadAssignmentsDistributed',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CSEYE',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='images/icon.ico',
)
