UnitsKey={
"lb_in_F":1,
"lb_ft_F":2,
"kip_in_F":3,
"kip_ft_F":4
}

AvailableTables = {
    "Area Assignments - Section Properties": {"DataType":["Framing"],
                                               "ViewTypes":["Story","Elevation"]},
    "Base Reactions": {"DataType":["Base Reactions"],
                        "ViewTypes":["Story","Elevation"]},
    "Composite Beam Design Envelope": {"DataType":["Composite Beam Design"],
                                                    "ViewTypes":["Story","Elevation"]},
    "Composite Beam Design Envelope - AISC 360-16": {"DataType":["Composite Beam Design"],
                                                    "ViewTypes":["Story","Elevation"]},
    "Element Forces - Beams": {"DataType":["Max Frame Forces","End Forces"],
                               "ViewTypes":["Story","Elevation"]},
    "Area Load Assignments - Uniform": {"DataType":["Load Assigns"],
                               "ViewTypes":["Story","Elevation"]},
    "Element Forces - Braces": {"DataType":["Max Frame Forces","End Forces"],
                                "ViewTypes":["Story","Elevation"]},
    "Element Forces - Columns": {"DataType":["Max Frame Forces","End Forces"],
                                 "ViewTypes":["Story","Elevation"]},
    "Diaphragm Forces": {"DataType":["Diaphragm Forces"],
                                     "ViewTypes":["Story"]},
    "Element Joint Forces - Frame": {"DataType":["Diaphragm Brace Forces"],
                                     "ViewTypes":["Story"]},
    "Frame Assignments - Property Modifiers": {"DataType":["Frame Modifiers"],
                                                        "ViewTypes":["Story","Elevation"]},
    "Frame Assignments - Releases and Partial Fixity": {"DataType":["Frame Releases"],
                                                        "ViewTypes":["Story","Elevation"]},
    "Frame Assignments - Section Properties": {"DataType":["Max Frame Forces","End Forces","Framing"],
                                               "ViewTypes":["Story","Elevation"]},
    "Frame Assignments - Summary": {"DataType":[],
                                    "ViewTypes":[]},
    "Frame Loads Assignments - Distributed": {"DataType":["Load Assigns"],
                                                        "ViewTypes":["Story","Elevation"]},
    "Frame Loads Assignments - Open Structure Wind Parameters": {"DataType":["Load Assigns"],
                                                        "ViewTypes":["Story","Elevation"]},
    "Joint Reactions": {"DataType":["Joint Reactions"],
                        "ViewTypes":["Story","Elevation"]},
    "Joint Displacements": {"DataType":["Joint Displacements"],
                            "ViewTypes":["Story","Elevation"]},
    "Joint Drifts": {"DataType":["Joint Drifts"],
                     "ViewTypes":["Story","Elevation"]},
    "Joint Loads Assignments - Force": {"DataType":["Load Assigns"],
                                                        "ViewTypes":["Story","Elevation"]},
    "Modal Case Definitions - Eigen": {"DataType":["Modal Properties"],
                        "ViewTypes":["Story","Elevation"]},
    "Modal Direction Factors": {"DataType":["Modal Properties"],
                        "ViewTypes":["Story","Elevation"]},
    "Modal Load Participation Ratios": {"DataType":["Modal Properties"],
                        "ViewTypes":["Story","Elevation"]},
    "Modal Participating Mass Ratios": {"DataType":["Modal Properties"],
                        "ViewTypes":["Story","Elevation"]},
    "Modal Participation Factors": {"DataType":["Modal Properties"],
                        "ViewTypes":["Story","Elevation"]},
    "Modal Periods And Frequencies": {"DataType":["Modal Properties"],
                        "ViewTypes":["Story","Elevation"]},
    'Steel Design Load Combination Data': {"DataType":["Steel Design 360-16"],
                                  "ViewTypes":["Story","Elevation"]},
    "Steel Frame Design Summary - AISC 360-16": {"DataType":["Steel Design 360-16"],
                                  "ViewTypes":["Story","Elevation"]},
    "Steel Beam Envelope - AISC 360-16": {"DataType":["Steel Design 360-16"],
                                  "ViewTypes":["Story","Elevation"]},
    "Steel Beam Deflection Envelope - AISC 360-16": {"DataType":["Steel Design 360-16"],
                                  "ViewTypes":["Story","Elevation"]},
    "Steel Brace Envelope - AISC 360-16": {"DataType":["Steel Design 360-16"],
                                  "ViewTypes":["Story","Elevation"]},
    "Steel Column Envelope - AISC 360-16": {"DataType":["Steel Design 360-16"],
                                  "ViewTypes":["Story","Elevation"]},
    "Story Forces": {"DataType":["Story Forces"],
                        "ViewTypes":["Story","Elevation"]},
}

