# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\vkanneh\Desktop\GitRepos\CSEYE\qtDesigner\windowLoadModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

def get_icon_path():
    """Get the absolute path to the icon file"""
    # Get the absolute path of the current file
    current_file = os.path.abspath(__file__)
    
    # Get the directory containing the current file
    current_dir = os.path.dirname(current_file)
    
    # Construct the path to the icon
    icon_path = os.path.join(os.path.dirname(current_dir), "images", "icon.png")

    
    return icon_path

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 664)
        icon = QtGui.QIcon()
        icon_path = get_icon_path()
        icon.addPixmap(QtGui.QPixmap(icon_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(75, 100))
        self.label_2.setMaximumSize(QtCore.QSize(75, 100))
        self.label_2.setStyleSheet("margin-botton:10px;")
        self.label_2.setText("")
        # Load icon for label
        icon_path = get_icon_path()
        pixmap = QtGui.QPixmap(icon_path)

        self.label_2.setPixmap(pixmap)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(500, 50))
        self.label.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"font: 32pt \"Arial Narrow\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.loadModelButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadModelButton.setMinimumSize(QtCore.QSize(300, 60))
        self.loadModelButton.setMaximumSize(QtCore.QSize(200, 60))
        self.loadModelButton.setStyleSheet("QPushButton{\n"
"min-height:60px;\n"
"max-height:60px;\n"
"max-width:200px;\n"
"border-radius:20px;\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.loadModelButton.setObjectName("loadModelButton")
        self.verticalLayout_4.addWidget(self.loadModelButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.modelPath = QtWidgets.QLabel(self.centralwidget)
        self.modelPath.setMinimumSize(QtCore.QSize(300, 20))
        self.modelPath.setMaximumSize(QtCore.QSize(300, 20))
        self.modelPath.setStyleSheet("/* horizontal only */\n"
"qproperty-alignment: AlignHCenter;\n"
"qproperty-alignment: AlignVCenter;\n"
"qproperty-alignment: AlignCenter;")
        self.modelPath.setText("")
        self.modelPath.setWordWrap(True)
        self.modelPath.setObjectName("modelPath")
        self.verticalLayout_5.addWidget(self.modelPath, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ETABS Toolbox"))
        self.label.setText(_translate("MainWindow", "CSEYE ETABS TOOLBOX"))
        self.loadModelButton.setText(_translate("MainWindow", "Load Model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
