# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\vkanneh\Desktop\GitRepos\CSEYE\qtDesigner\windowSelectViews.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

def get_icon_path():
    """Get the absolute path to the icon file"""
    # Get the absolute path of the current file
    current_file = os.path.abspath(__file__)
    print(f"Current file: {current_file}")
    
    # Get the directory containing the current file
    current_dir = os.path.dirname(current_file)
    print(f"Current directory: {current_dir}")
    
    # Construct the path to the icon
    icon_path = os.path.join(os.path.dirname(current_dir), "images", "icon.png")
    print(f"Attempting to load icon from: {icon_path}")
    
    # Check if file exists
    if os.path.exists(icon_path):
        print(f"Icon file exists at: {icon_path}")
    else:
        print(f"Icon file does not exist at: {icon_path}")
    
    return icon_path

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon_path = get_icon_path()
        print(f"Loading dialog icon from: {icon_path}")
        icon.addPixmap(QtGui.QPixmap(icon_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        if icon.isNull():
            print("Failed to load dialog icon - icon is null")
        else:
            print("Successfully loaded dialog icon")
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ViewsTypeLabel = QtWidgets.QLabel(Dialog)
        self.ViewsTypeLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.ViewsTypeLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ViewsTypeLabel.setObjectName("ViewsTypeLabel")
        self.verticalLayout.addWidget(self.ViewsTypeLabel, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.verticalLayout_3.addLayout(self.verticalLayout2)
        self.SaveViewButton = QtWidgets.QPushButton(Dialog)
        self.SaveViewButton.setMinimumSize(QtCore.QSize(0, 25))
        self.SaveViewButton.setMaximumSize(QtCore.QSize(16777215, 25))
        self.SaveViewButton.setStyleSheet("QPushButton{\n"
"min-height:30px;\n"
"max-height:60px;\n"
"border-radius:5px;\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"QMainWindow{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"*{\n"
"    font: 8pt \"Arial Narrow\";\n"
"}")
        self.SaveViewButton.setObjectName("SaveViewButton")
        self.verticalLayout_3.addWidget(self.SaveViewButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select views"))
        self.ViewsTypeLabel.setText(_translate("Dialog", "..."))
        self.SaveViewButton.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
